### ISSUE TITLE
compilation error in package moveit_core with g++ 9.3.0 

### ISSUE THREAD

**Issue by avinashiitk** [ros-planning/moveit2#279]
### Description
Does moveit2 support src build with g++ (GCC) 9.3.0?

### Your environment
* ROS Distro: Foxy
* OS Version: Ubuntu 18.04
* Source build
* Source build foxy branch

### Steps to reproduce
build fails with g++ (GCC) 9.3.0

### Expected behaviour
build should work with g++ 9.3.0

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by JafarAbdi** [comment]
> ### Your environment
> * ROS Distro: Foxy
> * OS Version: Ubuntu 18.04
> * Source build
> * Source build foxy branch

The foxy branch targets Ubuntu 20.04, not Ubuntu 18.04, so the build is expected to fail, please let me know if you have other questions
