### PR TITLE
RCLCPP Upgrade Bugfixes

### LINKED ISSUE #1178: Testing CI is broken with new version of rclcpp
We have a broken ci-testing with the changes from https://github.com/ros2/rclcpp/pull/1913. Currently working on fixing these.

### PR DESCRIPTION
**Pull request by DLu**
### Description

[CI is failing on #1176](https://github.com/ros-planning/moveit2/runs/5997775137?check_suite_focus=true#step:12:420) with the errors
```
/home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/controller_manager/controller_manager.h:141:67: error: no matching conversion for functional-style cast from 'int' to 'rclcpp::Duration'
    virtual bool waitForExecution(const rclcpp::Duration& timeout = rclcpp::Duration(-1)) = 0;
```
and
```
/home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/gripper_controller_handle.h:152:46: error: no viable overloaded '='
      send_goal_options.goal_response_callback =
```

I believe this is caused by https://github.com/ros2/rclcpp/pull/1913 and rclcpp getting a new release. 

Closes #1178 

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
@DLu thank yo so much for doing this. I think it also fails with:

```
/home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/gripper_controller_handle.h:152:46: error: no viable overloaded '='
      send_goal_options.goal_response_callback =
```

I couldn't figure this out really immediately, do you have any ideas? The related PR that breaks it: https://github.com/ros2/rclcpp/pull/1913

**Comment by DLu** [comment]
Refers to this line: https://github.com/ros-planning/moveit2/blob/438f6d208cea653238ea827f1c83ae901cedc360/moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/gripper_controller_handle.h#L152

**Comment by DLu** [comment]
Refers to this line: https://github.com/ros-planning/moveit2/blob/438f6d208cea653238ea827f1c83ae901cedc360/moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/gripper_controller_handle.h#L152

**Comment by vatanaksoytezer** [comment]
@DLu thank you! Just need to do the something for `follow_joint_trajectory_controller_handle`

**Review by JafarAbdi — APPROVED** [review]

**Review by vatanaksoytezer — APPROVED** [review]
